### ISSUE TITLE
Implement one-step slurping of script results into database

### ISSUE THREAD

**Issue by kspurgin** [UNC-Libraries/Syndetics-Catalog-Coverage-Assessment#10]
Either approach is ok: 
- set up database to import multiple csv files (one per collection) in one operation
  OR
- make script output one csv file containing results for all collections

**Comment by kspurgin** [comment]
I guess we've ended up with the "make script output one csv file containing results for all collections" option, and I think this was pretty close to being done, if not done. Yay.

**Comment by libbby** [comment]
Access database is set up for easy import of CSV's (output of 3rd script) that contain results for all collections indicated in the initial .txt file.
