### ISSUE TITLE
Report fields/columns

### ISSUE THREAD

**Issue by kspurgin** [UNC-Libraries/Syndetics-Catalog-Coverage-Assessment#26]
For each collection, report out the following columns: 
- Coll Recs - Number of records for that collection
- Coll URLs - Sum of primary_url_count for the records in collection
- Ebook % - Percentage of Coll Recs where the Endeca formats assigned include Ebook
- OCLC# % - Percentage of Coll Recs where oclc_boolean = 1
- Indexed Syndetics TOC % - Percentage of Coll Recs where toc_boolean = 1
- Display Syndetics TOC % (actual) - Percentage of Coll Recs that have Syndetics TOC displayed (from isbn1_toc_boolean, oclc_toc_boolean, upc_toc_boolean)
- Display Syndetics TOC % (potential) - Percentage of Coll Recs would have Syndetics TOC displayed if we sent through all ISBNs for match (from isbn1_toc_boolean, isbn2x_toc_boolean, oclc_toc_boolean, upc_toc_boolean)
- Display Syndetics Summary % (actual) - Percentage of Coll Recs that have Syndetics Summary displayed (from isbn1_summary_boolean, oclc_summary_boolean, upc_summary_boolean)
- Display Syndetics Summary % (potential) - Percentage of Coll Recs that would have Syndetics Summary displayed if we sent all ISBNs through for match (from isbn1_summary_boolean, isbn2x_summary_boolean, oclc_summary_boolean, upc_summary_boolean)
- Display Syndetics Chapter % (actual) - Percentage of Coll Recs that have Syndetics chapter preview displayed (from dbc booleans, excluding isbn2x) 
- Display Syndetics Chapter % (potential) - Percentage of Coll Recs that would have Syndetics chapter preview displayed if we sent through all ISBNs (from all dbc booleans) 
- Book Cover in Results % (actual) - Percentage of Coll Recs that have Syndetics book cover image (small) displayed in search results list (sc_boolean except isbn2x)
- Book Cover in Results % (potential) - Percentage of Coll Recs that would have Syndetics book cover image (small) displayed in search results list if all ISBNs sent through (sc_boolean)
- Book Cover in Full Record % (actual) - Percentage of Coll Recs that have Syndetics book cover image (medium) displayed in full record (mc_boolean except isbn2x)
- Book Cover in Full Record % (potential) - Percentage of Coll Recs that would have Syndetics book cover image (medium) displayed in full record if all ISBNs sent through (mc_boolean)
- LCC % - Percentage of Coll Recs that contain an LC Classification number
- SH (any) % - Percentage of Coll Recs that contain any subject headings (i.e. sum of LCSH COUNT, MESH COUNT, OTHER SH COUNT > 0)
- Controlled SH % - Percentage of Coll Recs that contain any controlled subject headings (sum of LCSH COUNT, MESH COUNT > 0)
- LCSH % - Percentage of Coll Recs that contain any LCSH
- MESH % - Percentage of Coll Recs that contain any MeSH
- Controlled SH density - Average number of controlled subject headings per record in collection
- Author access % - Percentage of Coll Recs that contain any Main Author or Other Author headings (i.e. main_author_boolean = 1 and/or other_author_count > 0)
- Author access density - Average number of author headings per record in collection (main authors and other authors counts combined)

I think that is sufficient for the report right out of Access. 

To prepare the report for actual delivery to the subject librarians, I would (a) remove the (potential) columns including the isbn2x results; (b) make sure the collection codes are replaced by collection names that will make sense to them; and (c): 
- Add a column for title list count -- total number of titles that are supposed to be in the collection (where we do have a title list) -- This data will unfortunately need to be put in manually based on analysis of the available title lists that have been identified (and live in H:\E-Books Working Group 2015-2016 )
- Add a column for marc coverage % - (total records / title list count, formatted as %)

**Comment by libbby** [comment]
These fields have been calculated and added to the report. Subject librarians on the e-books working group were asked for input as to the wording of each field.
