### ISSUE TITLE
Output count of Primary URL property values per record

### ISSUE THREAD

**Issue by kspurgin** [UNC-Libraries/Syndetics-Catalog-Coverage-Assessment#8]
Here's an example of the Endeca XML output when records have more than one Primary URL property: 

http://is.gd/xsopnK

The following needs to be added to URL to get this property: 
&include-record-property=Primary+URL

**Comment by libbby** [comment]
Script now provides count of Primary URLs per item. Tested with title collection examples and link from Kristina.
