### ISSUE TITLE
Script takes list of 773 collection titles as input

### ISSUE THREAD

**Issue by kspurgin** [UNC-Libraries/Syndetics-Catalog-Coverage-Assessment#9]
Edit so that script can take a txt file with one 773 collection title per line as its input, and produce output on all the collections listed. 

Some of our scripts hard code what the input file needs to be named and where it needs to be put in relation to the script itself. This is easier to document for staff who aren't very familiar with the command line. 

I imagine anyone using these scripts will be more comfortable with the command line, so you could also opt to pass the input file in as a parameter.

**Comment by libbby** [comment]
Script now takes input from a text file of MARC 773's. Text file to be used should be descriptively named MARC773s.txt. Have tested with two lines of MARC 773's, will run more.
